name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.24.0
  lottie: 2.7.0
  firebase_auth: 4.15.0
  introduction_screen: 3.1.12
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.6.3
  get_storage: 2.1.1
  cloud_firestore: 4.13.2
  intl: 0.19.0
  image_picker: 1.0.5
  firebase_storage: 11.3.0
  geolocator: 11.0.0
  geocoding: 2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/logo/chattoapps.png
  ios: true
  icon_size: 100
  min_sdk_android: 21

flutter:
  assets:
    - assets/logo/
    - assets/lottie/
  uses-material-design: true
